workflows:
  islamic-crossword-android:
    name: Islamic Crossword Android
    environment:
      android_sdk: "33"
      groups:
        - android_credentials
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Set up Android SDK
        script: |
          sdkmanager "platforms;android-30" "build-tools;30.0.3"
      - name: Build Debug APK
        script: |
          chmod +x ./gradlew
          ./gradlew assembleDebug
      - name: Build Release APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
      - app/build/outputs/apk/release/app-release-unsigned.apk
    publishing:
      email:
        recipients:
          - your-email@gmail.com
        notify:
          success: true
          failure: true
